- name: Ensure Docker, Docker-Compose, and Docker Swarm are installed
  hosts: manager
  become: yes
  become_user: root
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: latest
        update_cache: yes

    - name: Ensure Docker-Compose is Installed
      apt:
        name: docker-compose
        state: latest
        update_cache: yes

    - name: Add user to docker group
      user:
        name: retro
        groups: docker
