- name: Non Elevated Playbook
  hosts: picluster
  tasks:

    - name: GIT Clone Dotfiles into ~/git/dotfiles
      ansible.builtin.git:
        repo: https://github.com/retro956/dotfiles.git
        dest: ~/git/dotfiles
        version: master
      environment:
        GIT_TERMINAL_PROMPT: 0

    - name: GIT Clone Vundle
      ansible.builtin.git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim
        version: master
      environment:
        GIT_TERMINAL_PROMPT: 0

    - name: Copy tmux.conf
      ansible.builtin.copy:
        remote_src: true
        src: ~/git/dotfiles/tmux.conf
        dest: ~/.tmux.conf
        mode: '0755'

    - name: Copy .vimrc
      ansible.builtin.copy:
        remote_src: true
        src: ~/git/dotfiles/vimrc
        dest: ~/.vimrc
        mode: '0755'

    - name: Create ~/.vim/colors if not exists
      ansible.builtin.file:
        path: ~/.vim/colors
        state: directory
        mode: '0755'

    - name: Copy nachtleben.vim to ~/.vim/colors
      ansible.builtin.copy:
        remote_src: true
        src: ~/git/dotfiles/nachtleben.vim
        dest: ~/.vim/colors
        mode: '0755'

    - name: Trigger Vundle PluginInstall
      ansible.builtin.shell: vim -c "PluginInstall" -c qa
      register: vim_output
      changed_when: vim_output.rc != 0
