- name: Playbook to install software
  become: true
  hosts: ansible_hosts

  tasks:
    - name: Ensure vim is installed
      apt:
        name: vim
        state: present
        update_cache: true

    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: true

    - name: Ensure wget is installed
      apt:
        name: wget
        state: present
        update_cache: true

    - name: Ensure exuberant-ctags is installed for vim
      apt:
        name: exuberant-ctags
        state: present
        update_cache: true
