---
- name: Iterator demo
  hosts: all
  gather_facts: true

  tasks:
    - name: iterate through numbers
      command: echo {{ item }}
      with_items: [0, 1, 1, 2, 3, 5, 6, 13, 21, 34]
      when: item > 7
