- hosts: pi_cluster
  tasks:
    - name: Get Disk Usage - Copying Files
      copy:
        dest: /tmp/
        src: /media/data/ansible/ansible_playbooks/testing/main.py

    - name: Get Disk Usage - Execute Command
      shell: python /tmp/main.py
      register: pi_cluster_info
      notify: Get Disk Usage - Results

  handlers:
    - name: Get Disk Usage - Results
      debug:
        msg: "{{ pi_cluster_info.stdout }}"
