---
# tasks file for apt
- name: Update and Upgrade Repositories
  become: true
  become_user: root
  apt:
    update_cache: yes
    upgrade: yes
  tags:
    - apt_upgrade

- name: Ensure vim is installed
  become: true
  become_user: root
  apt:
    name: vim
    state: latest
  tags:
    - install_vim

- name: Ensure git is installed
  become: true
  become_user: root
  apt:
    name: git
    state: latest
  tags:
    - install_git

- name: Ensure wget is installed
  become: true
  become_user: root
  apt:
    name: wget
    state: latest
  tags:
    - install_wget

- name: Ensure exuberant-ctags is installed
  apt:
    name: exuberant-ctags
    state: latest
