---
# tasks file for apt
- name: Update and Upgrade Repositories
  become: true
  become_user: root
  apt:
    update_cache: yes
    upgrade: yes
  tags:
    - apt_upgrade

- name: Ensure packages are installed
  become: true
  become_user: root
  apt:
    name: ['vim', 'git', 'wget', 'tmux', 'exuberant-ctags']
    state: latest
  tags:
    - install_packages
